export type EmailTrack = {
  month: number
  theme: string
  couples1: EmailBlock
  husbands: EmailBlock
  wives: EmailBlock
  couples2: EmailBlock
}

export type EmailBlock = {
  subject: string
  title: string
  scripture: string
  scriptureRef: string
  focus: string
  action: string
  reflection: string
  prayer: string
}

export const MGM_EMAIL_CONTENT: EmailTrack[] = [
  {
    month: 1,
    theme: "Build your marriage on Christ",
    couples1: {
      subject: "Build Your Marriage on the Right Foundation",
      title: "Build Your Marriage on the Right Foundation",
      scripture: "Unless the Lord builds the house, those who build it labor in vain.",
      scriptureRef: "Psalm 127:1",
      focus: "Put Jesus back at the center of your home, your choices, and your love.",
      action: "Pray together for 3 minutes this week.",
      reflection: "What is currently shaping our marriage more than Christ?",
      prayer: "Lord Jesus, be the center of our home and teach us to build wisely.",
    },
    husbands: {
      subject: "Lead with Love, Not Control",
      title: "Lead with Love, Not Control",
      scripture: "Husbands, love your wives, as Christ loved the church and gave himself up for her.",
      scriptureRef: "Ephesians 5:25",
      focus: "Husband leadership is expressed through love, sacrifice, consistency, and service.",
      action: "Do one practical act of service for your wife this week without being asked.",
      reflection: "Does my wife experience me as safe, loving, and servant-hearted?",
      prayer: "Lord, teach me to love like Christ and lead with humility.",
    },
    wives: {
      subject: "Strengthen Your Marriage with Wisdom and Warmth",
      title: "Strengthen Your Marriage with Wisdom and Warmth",
      scripture: "The wisest of women builds her house, but folly with her own hands tears it down.",
      scriptureRef: "Proverbs 14:1",
      focus: "A wise wife strengthens the atmosphere of the home through grace, truth, and intentional love.",
      action: "Encourage your husband with one specific affirmation this week.",
      reflection: "What kind of atmosphere am I helping create in our marriage?",
      prayer: "Lord, make me wise, gracious, and strong in the way I build my home.",
    },
    couples2: {
      subject: "Your Monthly Marriage Check-In Starts Here",
      title: "Your Monthly Marriage Check-In Starts Here",
      scripture: "Two are better than one, because they have a good reward for their toil.",
      scriptureRef: "Ecclesiastes 4:9-10",
      focus: "Pause and review how you are doing together.",
      action: "Schedule 20 minutes this week and complete your check-in together.",
      reflection: "What do we need to pay attention to right now?",
      prayer: "Lord, help us walk in unity and support one another well.",
    },
  },
  {
    month: 2,
    theme: "Learn to hear each other well",
    couples1: {
      subject: "Strong Marriages Learn to Talk and Listen Well",
      title: "Strong Marriages Learn to Talk and Listen Well",
      scripture: "Let every person be quick to hear, slow to speak, slow to anger.",
      scriptureRef: "James 1:19",
      focus: "Healthy communication requires listening, gentleness, and timing.",
      action: "Have one 10-minute conversation with no phones and no interrupting.",
      reflection: "Do I listen to understand or to respond?",
      prayer: "Lord, teach us to be quick to listen, slow to speak, and full of grace.",
    },
    husbands: {
      subject: "She Needs to Feel Heard",
      title: "She Needs to Feel Heard",
      scripture: "Let every person be quick to hear, slow to speak, slow to anger.",
      scriptureRef: "James 1:19",
      focus: "Listening well is one of the clearest ways a husband loves his wife.",
      action: "Ask your wife, \"How are you really doing?\" and listen fully.",
      reflection: "Does my wife feel emotionally heard by me?",
      prayer: "Lord, help me listen with patience and love.",
    },
    wives: {
      subject: "Speak Life into Your Marriage",
      title: "Speak Life into Your Marriage",
      scripture: "Let no corrupting talk come out of your mouths, but only such as is good for building up.",
      scriptureRef: "Ephesians 4:29",
      focus: "Your words can strengthen, heal, and build connection.",
      action: "Replace one repeated complaint with one calm, honest request.",
      reflection: "Do my words build peace or pressure?",
      prayer: "Lord, make my words gracious, wise, and life-giving.",
    },
    couples2: {
      subject: "Pause, Listen, and Check In Together This Month",
      title: "Pause, Listen, and Check In Together This Month",
      scripture: "Bear with one another and, if one has a complaint against another, forgive each other.",
      scriptureRef: "Colossians 3:13-14",
      focus: "Reflect on how you are communicating and where you need grace.",
      action: "Complete your monthly check-in and ask, \"How can I support you better?\"",
      reflection: "What conversation have we been postponing?",
      prayer: "Lord, help us communicate with truth and tenderness.",
    },
  },
  {
    month: 3,
    theme: "Love must be demonstrated",
    couples1: {
      subject: "Love Grows When It Is Shown",
      title: "Love Grows When It Is Shown",
      scripture: "Let us not love in word or talk but in deed and in truth.",
      scriptureRef: "1 John 3:18",
      focus: "Love is strengthened when it is expressed through action, not assumption.",
      action: "Each spouse do one thoughtful act of love this week.",
      reflection: "What makes my spouse feel most loved right now?",
      prayer: "Lord, help us show love in practical ways.",
    },
    husbands: {
      subject: "5 Simple Ways to Demonstrate Love This Week",
      title: "5 Simple Ways to Demonstrate Love This Week",
      scripture: "Husbands, love your wives, and do not be harsh with them.",
      scriptureRef: "Colossians 3:19",
      focus: "Love your wife with gentleness, attention, and practical care.",
      action: "Plan one simple act of intentional kindness or connection.",
      reflection: "Is my love visible, or only assumed?",
      prayer: "Lord, make my love practical, gentle, and consistent.",
    },
    wives: {
      subject: "Honor Has the Power to Strengthen a Man",
      title: "Honor Has the Power to Strengthen a Man",
      scripture: "Love one another with brotherly affection. Outdo one another in showing honor.",
      scriptureRef: "Romans 12:10",
      focus: "Honor helps create safety, confidence, and warmth in marriage.",
      action: "Express one sincere appreciation for your husband's effort or character.",
      reflection: "Does my husband feel respected and valued by me?",
      prayer: "Lord, help me honor well and love deeply.",
    },
    couples2: {
      subject: "What Helped Your Marriage This Month?",
      title: "What Helped Your Marriage This Month?",
      scripture: "Love is patient and kind; love does not envy or boast; it is not arrogant.",
      scriptureRef: "1 Corinthians 13:4-7",
      focus: "Notice which actions increased closeness this month.",
      action: "Complete your check-in and share one thing each that made you feel loved.",
      reflection: "What practical habit should we keep building?",
      prayer: "Lord, teach us to love in ways that are felt and received.",
    },
  },
  {
    month: 4,
    theme: "Stay united under stress",
    couples1: {
      subject: "Don't Let Pressure Divide What God Joined",
      title: "Don't Let Pressure Divide What God Joined",
      scripture: "A threefold cord is not quickly broken.",
      scriptureRef: "Ecclesiastes 4:12",
      focus: "Pressure reveals patterns. Face stress as a team.",
      action: "Name the biggest pressure you are each carrying this week.",
      reflection: "When stress rises, do we move toward each other or away?",
      prayer: "Lord, keep us united under pressure.",
    },
    husbands: {
      subject: "How a Man Protects Peace at Home",
      title: "How a Man Protects Peace at Home",
      scripture: "A soft answer turns away wrath, but a harsh word stirs up anger.",
      scriptureRef: "Proverbs 15:1",
      focus: "Strength includes steadiness, patience, and self-control.",
      action: "Slow down one reaction this week and respond calmly.",
      reflection: "Does my presence bring peace or tension?",
      prayer: "Lord, make me steady, gentle, and strong.",
    },
    wives: {
      subject: "Bringing Peace into a Pressured Season",
      title: "Bringing Peace into a Pressured Season",
      scripture: "Let your reasonableness be known to everyone. The Lord is at hand.",
      scriptureRef: "Philippians 4:5-7",
      focus: "Peace grows through prayer, wisdom, and calm strength.",
      action: "Ask your husband one supportive question this week instead of assuming.",
      reflection: "What helps me stay soft and strong under stress?",
      prayer: "Lord, fill my heart with peace and wisdom.",
    },
    couples2: {
      subject: "What Pressure Are You Carrying Right Now?",
      title: "What Pressure Are You Carrying Right Now?",
      scripture: "Bear one another's burdens, and so fulfill the law of Christ.",
      scriptureRef: "Galatians 6:2",
      focus: "Carry each other's burdens with honesty and grace.",
      action: "Complete the monthly check-in and name your current pressure points.",
      reflection: "Where do we most need support right now?",
      prayer: "Lord, teach us to carry one another with love.",
    },
  },
  {
    month: 5,
    theme: "Fight for resolution, not victory",
    couples1: {
      subject: "Conflict Does Not Have to Break Your Marriage",
      title: "Conflict Does Not Have to Break Your Marriage",
      scripture: "Be angry and do not sin; do not let the sun go down on your anger.",
      scriptureRef: "Ephesians 4:26",
      focus: "Conflict handled well can deepen maturity and trust.",
      action: "Practice one calm repair conversation this week.",
      reflection: "Do we fight to understand, or to win?",
      prayer: "Lord, help us pursue peace and truth together.",
    },
    husbands: {
      subject: "Strength Is Not in Winning the Argument",
      title: "Strength Is Not in Winning the Argument",
      scripture: "Husbands, love your wives, and do not be harsh with them.",
      scriptureRef: "Colossians 3:19",
      focus: "A strong husband knows how to stay gentle and own his part.",
      action: "Say, \"I was wrong for…\" where needed this week.",
      reflection: "Am I easy to approach after tension?",
      prayer: "Lord, give me humility and self-control.",
    },
    wives: {
      subject: "How to Respond Without Tearing Down Connection",
      title: "How to Respond Without Tearing Down Connection",
      scripture: "A soft answer turns away wrath, but a harsh word stirs up anger.",
      scriptureRef: "Proverbs 15:1",
      focus: "Wise responses protect connection even in hard moments.",
      action: "Choose a softer opening line in one hard conversation this week.",
      reflection: "How can I speak honestly without attacking?",
      prayer: "Lord, help me respond with wisdom and grace.",
    },
    couples2: {
      subject: "Take a Marriage Reset This Month",
      title: "Take a Marriage Reset This Month",
      scripture: "Bearing with one another and, if one has a complaint against another, forgiving each other.",
      scriptureRef: "Colossians 3:13",
      focus: "Use your monthly review to identify what needs healing and repair.",
      action: "Complete your check-in and ask, \"Is there anything unresolved between us?\"",
      reflection: "What needs forgiveness, clarity, or repair?",
      prayer: "Lord, heal what is strained and soften our hearts.",
    },
  },
  {
    month: 6,
    theme: "Stay close, not just committed",
    couples1: {
      subject: "Great Marriages Stay Connected on Purpose",
      title: "Great Marriages Stay Connected on Purpose",
      scripture: "Enjoy life with the wife whom you love.",
      scriptureRef: "Ecclesiastes 9:9",
      focus: "Friendship is part of the strength of marriage.",
      action: "Share one enjoyable moment together this week.",
      reflection: "Are we still making room for laughter and closeness?",
      prayer: "Lord, renew joy and friendship in our marriage.",
    },
    husbands: {
      subject: "Pursue Her Again",
      title: "Pursue Her Again",
      scripture: "O my dove, in the clefts of the rock, let me see your face, let me hear your voice.",
      scriptureRef: "Song of Songs 2:14",
      focus: "Keep showing interest, tenderness, and initiative.",
      action: "Plan one intentional moment of connection this week.",
      reflection: "Am I still pursuing my wife with affection and attention?",
      prayer: "Lord, help me love my wife with warmth and intention.",
    },
    wives: {
      subject: "Keep the Warmth Alive in Your Marriage",
      title: "Keep the Warmth Alive in Your Marriage",
      scripture: "Love one another with brotherly affection. Outdo one another in showing honor.",
      scriptureRef: "Romans 12:10",
      focus: "Marriage thrives where warmth and intentionality are nurtured.",
      action: "Create one simple moment of affection or appreciation this week.",
      reflection: "What helps our connection feel alive?",
      prayer: "Lord, keep our marriage warm, tender, and alive.",
    },
    couples2: {
      subject: "When Is Your Next Date Night?",
      title: "When Is Your Next Date Night?",
      scripture: "Therefore a man shall leave his father and his mother and hold fast to his wife.",
      scriptureRef: "Genesis 2:24",
      focus: "Connection needs space and intention.",
      action: "Complete your check-in and put a date moment on the calendar.",
      reflection: "What keeps getting in the way of our connection?",
      prayer: "Lord, teach us to prioritize each other.",
    },
  },
  {
    month: 7,
    theme: "Build as one team",
    couples1: {
      subject: "Money Pressure Should Not Rule Your Marriage",
      title: "Money Pressure Should Not Rule Your Marriage",
      scripture: "The plans of the diligent lead surely to abundance.",
      scriptureRef: "Proverbs 21:5",
      focus: "Financial clarity and unity reduce fear and confusion.",
      action: "Set aside 20 minutes to discuss one financial priority.",
      reflection: "Are we facing money as partners or opponents?",
      prayer: "Lord, give us wisdom, discipline, and unity in stewardship.",
    },
    husbands: {
      subject: "Lead with Responsibility in Financial Matters",
      title: "Lead with Responsibility in Financial Matters",
      scripture: "If anyone does not provide for his relatives, and especially for members of his household, he has denied the faith.",
      scriptureRef: "1 Timothy 5:8",
      focus: "Financial leadership includes honesty, planning, and responsibility.",
      action: "Start or review one practical money plan with your wife.",
      reflection: "Am I transparent, responsible, and steady in this area?",
      prayer: "Lord, help me steward well and lead responsibly.",
    },
    wives: {
      subject: "Wisdom, Peace, and Partnership in Your Finances",
      title: "Wisdom, Peace, and Partnership in Your Finances",
      scripture: "She considers a field and buys it; with the fruit of her hands she plants a vineyard.",
      scriptureRef: "Proverbs 31:16",
      focus: "Wisdom in the home includes peace, prudence, and partnership.",
      action: "Have one calm conversation about a priority, not a complaint.",
      reflection: "How can I bring wisdom and peace into our financial conversations?",
      prayer: "Lord, give me wisdom and grace in the area of finances.",
    },
    couples2: {
      subject: "Have the Money Conversation You've Been Avoiding",
      title: "Have the Money Conversation You've Been Avoiding",
      scripture: "Can two walk together, unless they are agreed?",
      scriptureRef: "Amos 3:3",
      focus: "Agreement grows through honest conversation and shared priorities.",
      action: "Complete your check-in and identify one shared next step financially.",
      reflection: "What financial habit needs attention right now?",
      prayer: "Lord, align our hearts and help us build wisely.",
    },
  },
  {
    month: 8,
    theme: "Grow together before God",
    couples1: {
      subject: "Couples Who Pray Together Grow Stronger Together",
      title: "Couples Who Pray Together Grow Stronger Together",
      scripture: "If two of you agree on earth about anything they ask, it will be done for them.",
      scriptureRef: "Matthew 18:19-20",
      focus: "A marriage grows deeper when both spouses seek God together.",
      action: "Pray together twice this week, even if briefly.",
      reflection: "What keeps us from praying together more often?",
      prayer: "Lord Jesus, draw us close to You and closer to each other.",
    },
    husbands: {
      subject: "Lead Spiritually by Walking Closely with Jesus",
      title: "Lead Spiritually by Walking Closely with Jesus",
      scripture: "As for me and my house, we will serve the Lord.",
      scriptureRef: "Joshua 24:15",
      focus: "Spiritual leadership starts with personal surrender, not performance.",
      action: "Spend time with Jesus this week and share one takeaway with your wife.",
      reflection: "Is my private walk with God shaping my marriage?",
      prayer: "Lord, anchor me in You so I can lead with authenticity.",
    },
    wives: {
      subject: "Strengthen Your Home Through Prayer and Presence",
      title: "Strengthen Your Home Through Prayer and Presence",
      scripture: "God is in the midst of her; she shall not be moved.",
      scriptureRef: "Psalm 46:5",
      focus: "A wife's spiritual strength blesses the atmosphere of the home.",
      action: "Pray intentionally for your husband this week and tell him one thing you prayed.",
      reflection: "How can I bring Christ's peace into our home?",
      prayer: "Lord, make me steady, prayerful, and full of grace.",
    },
    couples2: {
      subject: "What Is God Saying to Your Marriage Right Now?",
      title: "What Is God Saying to Your Marriage Right Now?",
      scripture: "I am the vine; you are the branches. Whoever abides in me and I in him bears much fruit.",
      scriptureRef: "John 15:5",
      focus: "Reflect together on what God is shaping in your marriage.",
      action: "Complete your check-in and include one shared prayer request.",
      reflection: "Where do we sense God inviting growth?",
      prayer: "Lord, teach us to abide in You together.",
    },
  },
  {
    month: 9,
    theme: "Build the kind of home you want to leave behind",
    couples1: {
      subject: "Build a Home with Vision, Peace, and Purpose",
      title: "Build a Home with Vision, Peace, and Purpose",
      scripture: "As for me and my house, we will serve the Lord.",
      scriptureRef: "Joshua 24:15",
      focus: "Every home is shaped by repeated values, words, and habits.",
      action: "Name 3 values you want to define your home.",
      reflection: "What atmosphere are we creating daily?",
      prayer: "Lord, help us build a home that honors You.",
    },
    husbands: {
      subject: "The Kind of Home a Husband Helps Create",
      title: "The Kind of Home a Husband Helps Create",
      scripture: "He has told you, O man, what is good; and what does the Lord require of you but to do justice, and to love kindness, and to walk humbly.",
      scriptureRef: "Micah 6:8",
      focus: "Presence, consistency, and integrity shape the culture of a home.",
      action: "Do one thing this week that increases peace and stability at home.",
      reflection: "What kind of atmosphere follows my presence?",
      prayer: "Lord, help me shape my home with integrity and love.",
    },
    wives: {
      subject: "Your Influence Shapes the Atmosphere of the Home",
      title: "Your Influence Shapes the Atmosphere of the Home",
      scripture: "She opens her mouth with wisdom, and the teaching of kindness is on her tongue.",
      scriptureRef: "Proverbs 31:26",
      focus: "Your words, tone, and wisdom help define the home culture.",
      action: "Speak one life-giving word into your home each day this week.",
      reflection: "What atmosphere am I reinforcing?",
      prayer: "Lord, use me to build peace, strength, and warmth.",
    },
    couples2: {
      subject: "What Kind of Home Are You Building Together?",
      title: "What Kind of Home Are You Building Together?",
      scripture: "These words that I command you today shall be on your heart. You shall teach them diligently to your children.",
      scriptureRef: "Deuteronomy 6:6-7",
      focus: "Review the values and rhythms shaping your home.",
      action: "Complete your check-in and choose one family value to strengthen.",
      reflection: "What needs to start or stop in our home?",
      prayer: "Lord, shape our home for Your glory and our family's good.",
    },
  },
  {
    month: 10,
    theme: "Let grace do deep work",
    couples1: {
      subject: "Healing Begins Where Grace Is Welcomed",
      title: "Healing Begins Where Grace Is Welcomed",
      scripture: "Bear with one another and, if one has a complaint against another, forgive each other.",
      scriptureRef: "Colossians 3:13",
      focus: "Healing grows where repentance, grace, and truth are welcomed.",
      action: "Ask if there is anything that still needs healing between you.",
      reflection: "Are we carrying anything unresolved?",
      prayer: "Lord, heal the places that are still tender or strained.",
    },
    husbands: {
      subject: "A Real Man Knows How to Repent",
      title: "A Real Man Knows How to Repent",
      scripture: "Confess your sins to one another and pray for one another, that you may be healed.",
      scriptureRef: "James 5:16",
      focus: "Repentance is a strength that rebuilds trust.",
      action: "Offer one clear apology where needed this week.",
      reflection: "Am I willing to own my wrong without excuses?",
      prayer: "Lord, make me humble, honest, and teachable.",
    },
    wives: {
      subject: "Healing Your Marriage Without Hardening Your Heart",
      title: "Healing Your Marriage Without Hardening Your Heart",
      scripture: "And I will give you a new heart, and a new spirit I will put within you.",
      scriptureRef: "Ezekiel 36:26",
      focus: "Healing does not mean pretending; it means letting grace do its work wisely.",
      action: "Bring one hurt to God and one honest conversation to your husband.",
      reflection: "Where do I need God's healing in my heart?",
      prayer: "Lord, keep my heart soft, wise, and whole.",
    },
    couples2: {
      subject: "Is There Anything We Still Need to Heal?",
      title: "Is There Anything We Still Need to Heal?",
      scripture: "He heals the brokenhearted and binds up their wounds.",
      scriptureRef: "Psalm 147:3",
      focus: "Use this month's check-in to make room for healing.",
      action: "Complete your check-in and name one area needing grace or repair.",
      reflection: "What wound or pattern still needs attention?",
      prayer: "Lord, restore what has been bruised between us.",
    },
  },
  {
    month: 11,
    theme: "Protect tenderness in marriage",
    couples1: {
      subject: "Tenderness Matters in Marriage",
      title: "Tenderness Matters in Marriage",
      scripture: "Finally, all of you, have unity of mind, sympathy, brotherly love, a tender heart, and a humble mind.",
      scriptureRef: "1 Peter 3:8",
      focus: "Emotional closeness and gentle affection matter deeply.",
      action: "Share one affectionate, intentional moment this week.",
      reflection: "Do we feel emotionally close right now?",
      prayer: "Lord, renew tenderness and trust between us.",
    },
    husbands: {
      subject: "Love Her with Tenderness, Patience, and Care",
      title: "Love Her with Tenderness, Patience, and Care",
      scripture: "Husbands, live with your wives in an understanding way, showing honor to the woman as the weaker vessel.",
      scriptureRef: "1 Peter 3:7",
      focus: "Emotional safety, gentleness, and honor deepen intimacy.",
      action: "Offer affection and attention in a way your wife receives well.",
      reflection: "Does my wife feel safe, cherished, and pursued?",
      prayer: "Lord, teach me tenderness and honor.",
    },
    wives: {
      subject: "Nurture Closeness in Your Marriage with Warmth",
      title: "Nurture Closeness in Your Marriage with Warmth",
      scripture: "My beloved is mine, and I am his.",
      scriptureRef: "Song of Songs 2:16",
      focus: "Warmth, openness, and affection help maintain closeness.",
      action: "Create one moment of warmth and connection this week.",
      reflection: "What helps us feel near to each other?",
      prayer: "Lord, keep our bond tender, healthy, and strong.",
    },
    couples2: {
      subject: "How Can We Grow Closer This Month?",
      title: "How Can We Grow Closer This Month?",
      scripture: "Therefore a man shall leave his father and his mother and hold fast to his wife, and they shall become one flesh.",
      scriptureRef: "Genesis 2:24",
      focus: "Review emotional and relational closeness with honesty.",
      action: "Complete your check-in and plan one step toward deeper connection.",
      reflection: "What would help us feel closer right now?",
      prayer: "Lord, draw us nearer to each other in love.",
    },
  },
  {
    month: 12,
    theme: "Keep building, keep choosing each other",
    couples1: {
      subject: "Your Marriage Has a Legacy Beyond Yourselves",
      title: "Your Marriage Has a Legacy Beyond Yourselves",
      scripture: "We will tell the next generation the glorious deeds of the Lord.",
      scriptureRef: "Psalm 78:4-7",
      focus: "Your marriage shapes future generations and leaves a legacy.",
      action: "Talk about the kind of legacy you want your home to leave.",
      reflection: "What do we want our marriage to pass on?",
      prayer: "Lord, make our marriage fruitful beyond ourselves.",
    },
    husbands: {
      subject: "The Legacy of a Faithful Husband",
      title: "The Legacy of a Faithful Husband",
      scripture: "One who is faithful in a very little is also faithful in much.",
      scriptureRef: "Luke 16:10",
      focus: "Faithfulness in small things builds a lasting legacy.",
      action: "Choose one consistent habit to keep building next year.",
      reflection: "What kind of husband am I becoming over time?",
      prayer: "Lord, make me faithful, steady, and fruitful.",
    },
    wives: {
      subject: "The Legacy of a Wise and Strong Wife",
      title: "The Legacy of a Wise and Strong Wife",
      scripture: "Strength and dignity are her clothing, and she laughs at the time to come.",
      scriptureRef: "Proverbs 31:25-26",
      focus: "A wise and faithful wife leaves strength, grace, and blessing behind.",
      action: "Name one quality you want to strengthen for the next season.",
      reflection: "What legacy is my life creating in my home?",
      prayer: "Lord, make my life fruitful, wise, and full of grace.",
    },
    couples2: {
      subject: "End the Year Strong and Start Fresh Together",
      title: "End the Year Strong and Start Fresh Together",
      scripture: "The steadfast love of the Lord never ceases; his mercies never come to an end; they are new every morning.",
      scriptureRef: "Lamentations 3:22-23",
      focus: "Reflect with gratitude and enter the next season with fresh faith.",
      action: "Complete your year-end check-in and write one shared goal for the next season.",
      reflection: "What is God inviting us into next?",
      prayer: "Lord, thank You for Your mercy and for the work You are doing in our marriage.",
    },
  },
]

export function getEmailContent(month: number): EmailTrack | undefined {
  return MGM_EMAIL_CONTENT.find((t) => t.month === month)
}
